# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jxmh19aZB3p_v03m_3rUeG6IAUVZWodO
"""

# PROJECT 2 — Data Classification Using KNN

# STEP 1 — Import libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, f1_score, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# STEP 2 — Load dataset
iris = load_iris()
X = iris.data      # Features (4 columns)
y = iris.target    # Labels (0, 1, 2 = three species)

print("Dataset shape:", X.shape)
print("Classes:", iris.target_names)

# STEP 3 — Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

# STEP 4 — Scale features
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# STEP 5 — Train KNN model
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# STEP 6 — Predict
predictions = model.predict(X_test)

# STEP 7 — Evaluate
print("\nF1 Score:", f1_score(y_test, predictions, average='weighted'))
print("\nClassification Report:")
print(classification_report(y_test, predictions, target_names=iris.target_names))

# STEP 8 — Confusion Matrix
cm = confusion_matrix(y_test, predictions)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=iris.target_names,
            yticklabels=iris.target_names)
plt.title('Confusion Matrix — KNN on Iris Dataset')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()